Repository brain-tec/odoo-1, pull requests merged in 2020-10, with the labels that each got.

#2 [t118814] Migrates our contributions to the frePPLe connector to V13.
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/data/demo.xml
  frepple/data/mrp_routing.xml
  frepple/models/__init__.py
  frepple/models/product_product.py
  frepple/models/res_company.py
  frepple/models/res_config_settings.py
  frepple/models/res_partner.py
  frepple/models/sale_order_line.py
  frepple/tests/__init__.py
  frepple/tests/test_base.py
  frepple/tests/test_outbound_customers.py
  frepple/tests/test_outbound_items.py
  frepple/tests/test_outbound_locations.py
  frepple/tests/test_outbound_move_lines.py
  frepple/tests/test_outbound_saleorders.py
  frepple/tests/test_outbound_stock_rules.py
  frepple/views/res_company.xml
  frepple/views/res_config_settings_views.xml
Labels: 13.0.project_mi_465

#3 [t118814] Fixes the auxiliary methods for testing that are used in other modules.
  frepple/tests/test_base.py
Labels: 13.0.project_mi_465

#4 [t118814] Fix: Parameter ctx was not guaranteed to be iterable.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#5 [t118814] Fix: <operationplan> exported unknown attribute 'locked', and 'start' and 'end' were not compliant.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#6 [t118814] Fix on <operationplan>: bad call to replace() over a datetime.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#7 Syncing from upstream frePPLe/odoo (10.0)
  frepple/controllers/outbound.py
Labels: 10.0

#8 Syncing from upstream frePPLe/odoo (11.0)
  frepple/controllers/outbound.py
Labels: 11.0

#9 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#10 Syncing from upstream frePPLe/odoo (13.0)
  frepple/controllers/outbound.py
Labels: 13.0

#11 [t118814] Locations are exported with its complete name. Move Lines having the same location for From & To are ignored.
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/tests/test_outbound_locations.py
  frepple/tests/test_outbound_move_lines.py
Labels: 13.0.project_mi_465

#12 Syncing from upstream frePPLe/odoo (10.0)
  frepple/controllers/outbound.py
Labels: 10.0

#13 Syncing from upstream frePPLe/odoo (11.0)
  frepple/controllers/outbound.py
Labels: 11.0

#14 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#15 Syncing from upstream frePPLe/odoo (13.0)
  frepple/controllers/outbound.py
Labels: 13.0

#16 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#17 Syncing from upstream frePPLe/odoo (13.0)
  frepple/controllers/outbound.py
Labels: 13.0

#19 [t118814][bt#12120] Changes in frePPLe & Update of our code with frePPLe's newest changes.
  frepple/controllers/frepplexml.py
  frepple/controllers/outbound.py
  frepple/tests/test_base.py
  frepple/tests/test_outbound_items.py
  frepple/tests/test_outbound_move_lines.py
  frepple/tests/test_outbound_saleorders.py
  frepple/tests/test_outbound_stock_rules.py
Labels: 13.0.project_mi_465

#18 [t118814][bt#12120] Updating 13.0.project_MI_465 from 13.0
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#20 Syncing from upstream frePPLe/odoo (10.0)
  frepple/controllers/outbound.py
Labels: 10.0
