Repository brain-tec/odoo-1, pull requests merged in 2020-11, with the labels that each got.

#21 [t119072] Refactors the method export_items to make it easier to monkey-patch it.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#22 [t119072] Refactors the method export_items to make it easier to monkey-patch it.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#23 [t119072] Fixes a very-bad indentation.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#24 [t119072] Implements the import of a Distribution Order in frePPLe
  frepple/controllers/inbound.py
  frepple/controllers/outbound.py
  frepple/models/__init__.py
  frepple/models/stock_move_line.py
  frepple/tests/__init__.py
  frepple/tests/test_base.py
  frepple/tests/test_inbound_ordertype_do.py
Labels: 13.0.project_mi_465

#25 [t119072] <demand>s that represent a sale.order have a fixed priority of 10.
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#31 [t119072] Status of a <demand> is exported with the attribute "status" and not "description".
  frepple/controllers/outbound.py
  frepple/tests/test_outbound_saleorders.py
Labels: 13.0.project_mi_465

#32 [t119072] Extracts the computation of a customer's name when exporting the customers.
  frepple/controllers/outbound.py
  frepple/models/res_partner.py
Labels: 13.0.project_mi_465

#33 Syncing from upstream frePPLe/odoo (11.0)
  frepple/controllers/outbound.py
Labels: 11.0

#34 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#35 Syncing from upstream frePPLe/odoo (13.0)
  frepple/controllers/outbound.py
Labels: 13.0

#36 [t119072] Changes the format of the input <operationplan>
  frepple/__manifest__.py
  frepple/models/stock_move_line.py
  frepple/tests/test_inbound_ordertype_do.py
Labels: 13.0.project_mi_465

#38 [t119072] Prepare this fork to use brain-tec's approach to Docker
  .braintec/deploy.yaml
Labels: 13.0.project_mi_465
