Repository brain-tec/odoo-1, pull requests merged in 2021-02, with the labels that each got.

#53 [bt#12719] Further improvements in Frepple
  frepple/controllers/outbound.py
  frepple/models/mrp_production.py
  frepple/tests/test_inbound_ordertype_do.py
  frepple/tests/test_inbound_ordertype_mo.py
  frepple/tests/test_outbound_items.py
Labels: bug, enhancement

#54 FIX quoteattr in MO export
  frepple/controllers/outbound.py
Labels: 13.0.project_branch_mi_465.bt#12719

#55 [bt#12719] IMP better exclude
  frepple/controllers/outbound.py
Labels: 13.0.project_branch_mi_465.bt#12719

#56 [bt#12719] Updating operation(bom) representation in MO outbound
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465, bug, enhancement

#57 Syncing from upstream frePPLe/odoo (10.0)
  frepple/controllers/outbound.py
Labels: 10.0

#58 Syncing from upstream frePPLe/odoo (11.0)
  frepple/controllers/outbound.py
Labels: 11.0

#59 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#60 Syncing from upstream frePPLe/odoo (13.0)
  frepple/controllers/outbound.py
Labels: 13.0

#61 [bt#12719] Refactoring inbound, to have imported_pos and imported_pic…
  frepple/__manifest__.py
  frepple/controllers/inbound.py
  frepple/models/__init__.py
  frepple/models/mrp_production.py
  frepple/models/purchase_order.py
  frepple/models/purchase_order_line.py
  frepple/models/stock_move.py
  frepple/models/stock_move_line.py
  frepple/tests/test_base.py
  frepple/tests/test_inbound_ordertype_do.py
  frepple/tests/test_inbound_ordertype_po.py
  frepple/views/purchase_order_views.xml
  frepple/views/stock_move_line_views.xml
  frepple/views/stock_picking_views.xml
Labels: 13.0.project_mi_465, enhancement

#62 [bt#12719] Key for existing inbound POs take now into account also lo…
  frepple/models/purchase_order_line.py
Labels: 13.0.project_mi_465, enhancement

#64 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#65 [bt#12719] Changing outbound from move lines to moves. Adapting tests…
  frepple/controllers/outbound.py
  frepple/models/purchase_order_line.py
  frepple/models/stock_move.py
  frepple/tests/__init__.py
  frepple/tests/test_base.py
  frepple/tests/test_inbound_ordertype_do.py
  frepple/tests/test_inbound_ordertype_po.py
  frepple/tests/test_outbound_moves.py
Labels: 13.0.project_mi_465, enhancement

#66 [bt#12719] Changing related model for domain config for moves
  frepple/views/res_company.xml
Labels: 13.0.project_mi_465

#67 [bt#13353] Small Improvements for Ticket bt#13353
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/models/mrp_production.py
  frepple/models/purchase_order_line.py
  frepple/models/stock_move.py
Labels: 13.0.project_mi_465
