Repository brain-tec/odoo-1, pull requests merged in 2021-07, with the labels that each got.

#97 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#98 Syncing from upstream frePPLe/odoo (13.0)
  frepple/controllers/outbound.py
Labels: 13.0

#99 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#101 Updating 13.0.project_MI_465.test from latest 13.0.project_MI_465
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465.test
