Repository brain-tec/odoo-1, pull requests merged in 2021-03, with the labels that each got.

#68 [bt#13498] Skipping SO lines related to delivery costs to fix frepple…
  frepple/models/sale_order_line.py
Labels: 13.0.project_mi_465, bug

#70 Syncing from upstream frePPLe/odoo (14.0)
  frepple/static/src/js/frepple.js
Labels: 14.0

#72 [bt#13660] Adapting inbound PO to summarize PO lines having same product
  frepple/models/purchase_order_line.py
  frepple/tests/test_inbound_ordertype_po.py
Labels: 13.0.project_mi_465.test, enhancement

#74 [bt#13660] Small improvement to have the method ready to be extended
  frepple/models/purchase_order_line.py
Labels: 13.0.project_mi_465.test, enhancement

#75 [bt#13660] Refactoring tests for inbound PO to make them easier to be…
  frepple/tests/__init__.py
  frepple/tests/test_base_inbound_ordertype_po.py
  frepple/tests/test_inbound_ordertype_po.py
Labels: 13.0.project_mi_465.test, enhancement

#76 [bt#13660] Improvements & bugfixes tests inbound PO
  frepple/tests/test_base_inbound_ordertype_po.py
Labels: 13.0.project_mi_465.test, bug, enhancement

#77 [bt#13660] Inbound PO receive frepple reference as "id" instead of "r…
  frepple/controllers/inbound.py
  frepple/models/purchase_order_line.py
  frepple/tests/test_base_inbound_ordertype_po.py
  frepple/tests/test_inbound_ordertype_po.py
Labels: 13.0.project_mi_465.test, bug

#73 [bt#13660] Adapting inbound PO to summarize PO lines having same product
  frepple/controllers/inbound.py
  frepple/models/purchase_order_line.py
  frepple/tests/__init__.py
  frepple/tests/test_base_inbound_ordertype_po.py
  frepple/tests/test_inbound_ordertype_po.py
Labels: 13.0.project_mi_465, enhancement

#79 Updating from latest Frepple 13.0
  frepple/static/src/js/frepple.js
Labels: 13.0.project_mi_465

#80 Back-merge from latest 13.0.project_MI_465 into 13.0.project_MI_465.test
  frepple/static/src/js/frepple.js
Labels: 13.0.project_mi_465.test

#81 Update 20210323: Updating code for creating a product in tests of fre…
  frepple/tests/test_base.py
Labels: 13.0.project_mi_465, enhancement

#82 Update 20210323: Back-merge for frepple from 13.0.project_MI_465 into 13.0.project_MI_465.test
  frepple/tests/test_base.py
Labels: 13.0.project_mi_465.test

#83 Update 20210323: Bugfix for tests in frepple lots
  frepple/tests/test_base.py
Labels: 13.0.project_mi_465, bug

#84 Update 20210323: Back-merge Bugfix for tests in frepple lots
  frepple/tests/test_base.py
Labels: 13.0.project_mi_465.test
