Repository brain-tec/odoo-1, pull requests merged in 2021-01, with the labels that each got.

#42 [bt#12811] Urgent Fixes for Frepple
  frepple/models/sale_order_line.py
  frepple/tests/test_outbound_saleorders.py
Labels: 13.0.project_mi_465

#43 [bt#12811] Urgent Fixes for Frepple
  frepple/models/sale_order_line.py
  frepple/tests/test_outbound_saleorders.py
Labels: 13.0.project_mi_465

#44 [bt#12862] Frepple: Product Export Incomplete
  frepple/controllers/outbound.py
  frepple/models/res_company.py
  frepple/models/res_config_settings.py
  frepple/models/sale_order_line.py
  frepple/tests/test_outbound_move_lines.py
  frepple/tests/test_outbound_saleorders.py
  frepple/views/res_company.xml
  frepple/views/res_config_settings_views.xml
Labels: 13.0.project_mi_465

#47 [bt#12719] Exporting supplier info just for warehouses in which the p…
  frepple/controllers/outbound.py
  frepple/scripts/download_XML_local.sh
  frepple/scripts/xml/frepple_6.11.0.xsd
Labels: 13.0.project_mi_465, bug, enhancement

#48 [bt#12719] Bugifx when creating a MO from inbound xml, as it wasn't c…
  frepple/__manifest__.py
  frepple/controllers/inbound.py
  frepple/models/__init__.py
  frepple/models/mrp_production.py
  frepple/tests/test_base.py
  frepple/tests/test_inbound_ordertype_mo.py
  frepple/views/mrp_production.xml
Labels: 13.0.project_mi_465, bug, enhancement

#49 [bt#12719] Adding missing new test file
  frepple/tests/__init__.py
Labels: 13.0.project_mi_465, bug

#50 [bt#12719] Improvements on PO from inbound
  frepple/controllers/inbound.py
  frepple/models/__init__.py
  frepple/models/mrp_production.py
  frepple/models/purchase_order.py
  frepple/tests/__init__.py
  frepple/tests/test_inbound_ordertype_po.py
Labels: 13.0.project_mi_465, bug, enhancement

#51 [bt#12719] Improvements on Inbound DO
  frepple/__manifest__.py
  frepple/controllers/inbound.py
  frepple/models/mrp_production.py
  frepple/models/purchase_order.py
  frepple/models/stock_move_line.py
  frepple/tests/test_inbound_ordertype_do.py
  frepple/views/stock_move_line_views.xml
Labels: 13.0.project_mi_465, bug, enhancement
