Repository brain-tec/odoo-1, pull requests merged in 2021-04, with the labels that each got.

#85 Syncing from upstream frePPLe/odoo (12.0)
  autologin/controllers/controllers.py
  frepple/controllers/outbound.py
  frepple/models/res_company.py
Labels: 12.0

#86 Syncing from upstream frePPLe/odoo (13.0)
  autologin/controllers/controllers.py
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/data/demo.xml
  frepple/models/res_company.py
Labels: 13.0

#87 Syncing from upstream frePPLe/odoo (14.0)
  autologin/controllers/controllers.py
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/data/demo.xml
  frepple/models/res_company.py
Labels: 14.0

#90 [bt#13983] frePPLe improvements
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/models/res_company.py
  frepple/tests/test_outbound_items.py
  frepple/views/res_company.xml
Labels: 13.0.project_mi_465.test

#91 [bt#13983][FIX] Use an ID to browse a record
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465.test

#92 [bt#13983][FIX] Translations are considered when exporting
  frepple/controllers/outbound.py
  frepple/tests/test_base.py
  frepple/tests/test_outbound_items.py
  frepple/tests/test_outbound_saleorders.py
Labels: 13.0.project_mi_465.test

#89 [bt#13983] frePPLe improvements
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/models/res_company.py
  frepple/tests/test_base.py
  frepple/tests/test_outbound_items.py
  frepple/tests/test_outbound_saleorders.py
  frepple/views/res_company.xml
Labels: 13.0.project_mi_465

#94 Update 2021-04-13: Updating from 13.0
  autologin/controllers/controllers.py
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/data/demo.xml
  frepple/models/res_company.py
Labels: 13.0.project_mi_465.test

#96 [t120325] Accept Child Locations in Operation Type Search
  frepple/__manifest__.py
  frepple/models/stock_move.py
Labels: 13.0.project_mi_465.test
