Repository brain-tec/odoo-1, pull requests merged in 2022-11, with the labels that each got.

#248 Syncing from upstream frePPLe/odoo (14.0)
  README.md
  frepple/controllers/frepplexml.py
  freppledata/__manifest__.py
  freppledata/data/mrp.bom.csv
  freppledata/data/mrp.workcenter.csv
Labels: 14.0

#249 Syncing from upstream frePPLe/odoo (15.0)
  freppledata/__manifest__.py
  freppledata/data/mrp.bom.csv
  freppledata/data/mrp.workcenter.csv
Labels: 15.0

#250 Syncing from upstream frePPLe/odoo (16.0)
  freppledata/__manifest__.py
Labels: 16.0

#251 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
  freppledata/__manifest__.py
Labels: 14.0

#252 Syncing from upstream frePPLe/odoo (15.0)
  freppledata/__manifest__.py
Labels: 15.0

#253 Syncing from upstream frePPLe/odoo (16.0)
  freppledata/__manifest__.py
Labels: 16.0

#255 [bt#20802] fix inconsistency in quantity conversion
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465.test

#257 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/frepplexml.py
  frepple/controllers/inbound.py
Labels: 16.0

#254 [bt#20802] fix inconsistency in quantity conversion
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#95 [t120325] Accept Child Locations in Operation Type Search
  frepple/__manifest__.py
  frepple/models/stock_move.py
Labels: 13.0.project_mi_465

#260 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/frepplexml.py
  frepple/controllers/outbound.py
Labels: 15.0

#261 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/frepplexml.py
Labels: 16.0

#262 Syncing from upstream frePPLe/odoo (15.0)
  frepple/__init__.py
  frepple/controllers/outbound.py
  frepple/models/__init__.py
  frepple/models/res_company.py
  frepple/models/res_config_settings.py
Labels: 15.0
