Repository brain-tec/odoo-1, pull requests merged in 2022-12, with the labels that each got.

#263 Syncing from upstream frePPLe/odoo (14.0)
  README.md
  freppledata/data/product.template.csv
Labels: 14.0

#264 Syncing from upstream frePPLe/odoo (16.0)
  freppledata/__manifest__.py
Labels: 16.0

#265 Syncing from upstream frePPLe/odoo (14.0)
  frepple/security/frepple_security.xml
  freppledata/__manifest__.py
  freppledata/data/config.xml
Labels: 14.0

#266 Syncing from upstream frePPLe/odoo (15.0)
  README.md
  frepple/controllers/frepplexml.py
  frepple/controllers/outbound.py
  frepple/security/frepple_security.xml
  freppledata/__manifest__.py
  freppledata/data/config.xml
  freppledata/data/product.template.csv
Labels: 15.0

#267 Syncing from upstream frePPLe/odoo (16.0)
  README.md
  frepple/controllers/outbound.py
  frepple/security/frepple_security.xml
  freppledata/__manifest__.py
  freppledata/data/config.xml
  freppledata/data/product.template.csv
Labels: 16.0

#268 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#269 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/outbound.py
Labels: 15.0

#270 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0

#271 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#256 [t132054] Migration to 15.0 of Frepple with project_MI_465 mods.
  .braintec/deploy.yaml
  frepple/__init__.py
  frepple/__manifest__.py
  frepple/controllers/frepplexml.py
  frepple/controllers/inbound.py
  frepple/controllers/outbound.py
  frepple/misc/__init__.py
  frepple/misc/helper_datetime.py
  frepple/misc/tree.py
  frepple/models/__init__.py
  frepple/models/mrp_production.py
  frepple/models/product_product.py
  frepple/models/purchase_order_line.py
  frepple/models/res_company.py
  frepple/models/res_config_settings.py
  frepple/models/res_partner.py
  frepple/models/sale_order_line.py
  frepple/models/stock_location.py
  frepple/models/stock_move.py
  frepple/scripts/download_XML_local.sh
  frepple/scripts/xml/frepple_6.11.0.xsd
  frepple/static/src/js/frepple.js
  frepple/tests/__init__.py
  frepple/tests/test_base.py
  frepple/tests/test_base_inbound_ordertype_po.py
  frepple/tests/test_inbound_ordertype_do.py
  frepple/tests/test_inbound_ordertype_mo.py
  frepple/tests/test_inbound_ordertype_po.py
  frepple/tests/test_outbound_customers.py
  frepple/tests/test_outbound_items.py
  frepple/tests/test_outbound_locations.py
  frepple/tests/test_outbound_moves.py
  frepple/tests/test_outbound_saleorders.py
  frepple/tests/test_outbound_stock_rules.py
  frepple/tests/test_stock_location.py
  frepple/tests/test_tree.py
  frepple/views/mrp_production.xml
  frepple/views/purchase_order_views.xml
  frepple/views/res_company.xml
  frepple/views/res_config_settings_views.xml
  frepple/views/stock_picking_views.xml
  requirements.txt
Labels: 15.0.project_mi_465

#272 [t132054] Fixing frepple_lots tests. When running all modules integra…
  frepple/tests/test_base.py
Labels: 15.0.project_mi_465
