Repository brain-tec/odoo-1, pull requests merged in 2022-01, with the labels that each got.

#114 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/inbound.py
Labels: 14.0

#115 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#116 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#117 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#119 [t126547] For Frepple outbound BoM, location name is computed accordi…
  frepple/controllers/outbound.py
  frepple/scripts/xml/frepple_6.11.0.xsd
Labels: enhancement, 13.0.project_mi_465.test

#121 [t127249] Switching receipt date for inbound PO to end element, inste…
  frepple/models/purchase_order_line.py
Labels: bug, 13.0.project_mi_465.test
