Repository brain-tec/odoo-1, pull requests merged in 2022-02, with the labels that each got.

#125 [t126549] Changing the date planned to the received element end also …
  frepple/models/purchase_order_line.py
  frepple/tests/test_base_inbound_ordertype_po.py
Labels: bug, 13.0.project_mi_465.test

#127 [t127249] Changing logic to compute PO date_planned according to rece…
  frepple/controllers/inbound.py
  frepple/models/purchase_order_line.py
  frepple/tests/test_base_inbound_ordertype_po.py
Labels: bug, 13.0.project_mi_465.test

#128 [t127249] Frepple inbound: Transforming received dates from frepple to UTC
  frepple/misc/__init__.py
  frepple/misc/helper_datetime.py
  frepple/models/mrp_production.py
  frepple/models/purchase_order_line.py
  frepple/models/stock_move.py
Labels: enhancement, 13.0.project_mi_465.test

#129 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#130 [t127250] Changing weight to be an attribute instead of an element
  frepple/controllers/outbound.py
Labels: enhancement, 13.0.project_mi_465.test

#118 [t126547] Location Name for outbound BoM & updated XSD
  frepple/controllers/outbound.py
  frepple/scripts/xml/frepple_6.11.0.xsd
Labels: enhancement, 13.0.project_mi_465

#120 [t127249] Switching receipt date for inbound PO to end element, inste…
  frepple/controllers/frepplexml.py
  frepple/controllers/inbound.py
  frepple/misc/__init__.py
  frepple/misc/helper_datetime.py
  frepple/models/mrp_production.py
  frepple/models/purchase_order_line.py
  frepple/models/stock_move.py
  frepple/tests/test_base_inbound_ordertype_po.py
Labels: bug, 13.0.project_mi_465

#133 [t127250] Revert Changing weight to be an attribute instead of an element
  frepple/controllers/outbound.py
Labels: enhancement, 13.0.project_mi_465.test

#134 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/inbound.py
Labels: 14.0

#135 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/inbound.py
Labels: 14.0
