Repository brain-tec/odoo-1, pull requests merged in 2022-03, with the labels that each got.

#139 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/frepplexml.py
  frepple/controllers/inbound.py
  frepple/controllers/outbound.py
Labels: 14.0

#136 [t127763] Fixing issues with precision digits in outbound SO qty
  frepple/misc/helper_datetime.py
  frepple/models/sale_order_line.py
  frepple/tests/test_outbound_saleorders.py
Labels: bug, 13.0.project_mi_465

#138 [bt#18566] quick fix for the mix-up between product ids and product template ids
  frepple/controllers/outbound.py
Labels: bug, 13.0.project_mi_465

#142 [bt#18566] quick fix for the mix-up between product ids and product template ids
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465.test

#143 [bt#18566] quick fix for the mix-up between product ids and product template ids
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#146 [bt#18566] Revert of quick fix for the mix-up between product ids and product template ids
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465.test

#148 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/inbound.py
Labels: 14.0

#149 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/frepplexml.py
Labels: 14.0

#150 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#151 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#152 [HOTFIX] Hotfixed NoneType value for weight
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465

#153 Backmerge 13.0.project_MI_465 into 13.0.project_MI_465.test
  frepple/controllers/outbound.py
Labels: 13.0.project_mi_465.test

#154 Syncing from upstream frePPLe/odoo (12.0)
  frepple/controllers/outbound.py
Labels: 12.0

#155 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0
