Repository brain-tec/odoo-1, pull requests merged in 2023-10, with the labels that each got.

#366 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/frepplexml.py
  frepple/controllers/inbound.py
  frepple/controllers/outbound.py
  frepple/models/mrp_workorder_inherit.py
Labels: 16.0

#367 [t141840] Changed some views, repeated external_id removed
  frepple/views/frepple_data.xml
  frepple/views/res_company.xml
Labels: 15.0.project_mi_465

#368 Syncing from upstream frePPLe/odoo (14.0)
  frepple/controllers/outbound.py
Labels: 14.0

#369 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/outbound.py
Labels: 15.0

#372 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/inbound.py
  frepple/controllers/outbound.py
Labels: 15.0

#373 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/inbound.py
Labels: 16.0
