Repository brain-tec/odoo-1, pull requests merged in 2024-04, with the labels that each got.

#429 [bt#26759][FIX] Fixing exported quantity
  frepple/controllers/outbound.py
Labels: 15.0.project_mi_465

#430 Syncing from upstream frePPLe/odoo (17.0)
  frepple/__init__.py
  frepple/__manifest__.py
  frepple/controllers/outbound.py
  frepple/models/__init__.py
  frepple/models/quote.py
  frepple/models/res_company.py
  frepple/models/res_config_settings.py
  frepple/models/sale_order.py
  frepple/security/frepple_security.xml
  frepple/security/ir.model.access.csv
  frepple/views/quote_views.xml
  frepple/views/res_config_settings_views_no_mrp.xml
  frepple/views/sale_views.xml
Labels: 17.0

#432 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/outbound.py
Labels: 15.0

#433 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0

#434 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/outbound.py
Labels: 17.0

#435 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0

#436 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0
