Repository brain-tec/odoo-1, pull requests merged in 2024-12, with the labels that each got.

#492 [bt#28569] Take a location, depending on the BOM operation type
  frepple/controllers/outbound.py
Labels: 15.0.project_mi_465

#493 Syncing from upstream frePPLe/odoo (18.0)
  frepple/controllers/outbound.py
Labels: 18.0

#494 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/inbound.py
Labels: 17.0

#496 Syncing from upstream frePPLe/odoo (18.0)
  frepple/controllers/inbound.py
Labels: 18.0

#497 [bt#29520][bt#29446] Change Purchase Order Export Location
  frepple/controllers/outbound.py
Labels: 15.0.project_mi_465
