Repository brain-tec/odoo-1, pull requests merged in 2024-06, with the labels that each got.

#444 Syncing from upstream frePPLe/odoo (16.0)
  dockerfile
  frepple/__manifest__.py
  frepple/controllers/frepplexml.py
  frepple/models/res_company.py
Labels: 16.0

#445 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0

#446 Syncing from upstream frePPLe/odoo (17.0)
  dockerfile
  frepple/__manifest__.py
  frepple/controllers/frepplexml.py
  frepple/controllers/inbound.py
  frepple/controllers/outbound.py
  frepple/models/mrp_workorder_inherit.py
  frepple/models/res_company.py
Labels: 17.0

#447 Syncing from upstream frePPLe/odoo (17.0)
  frepple/models/quote.py
  frepple/models/sale_order.py
Labels: 17.0

#448 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/outbound.py
Labels: 17.0

#449 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/frepplexml.py
  frepple/controllers/outbound.py
Labels: 15.0

#450 [t149841][bt#27731] Removed a unnecesary qty conversion in flowplans. Added respect reservations to the frepple tab in the companies view
  frepple/controllers/outbound.py
  frepple/views/res_company.xml
Labels: 15.0.project_mi_465
