Repository brain-tec/odoo-1, pull requests merged in 2024-08, with the labels that each got.

#463 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/outbound.py
Labels: 15.0

#464 Syncing from upstream frePPLe/odoo (17.0)
  frepple/views/quote_views.xml
  frepple/views/sale_views.xml
Labels: 17.0

#465 Syncing from upstream frePPLe/odoo (15.0)
  frepple/controllers/outbound.py
Labels: 15.0

#466 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0

#467 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/outbound.py
  frepple/views/sale_views.xml
Labels: 17.0

#468 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/outbound.py
Labels: 17.0

#470 Syncing from upstream frePPLe/odoo (16.0)
  frepple/controllers/outbound.py
Labels: 16.0

#471 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/outbound.py
Labels: 17.0

#469 [bt#28702] Fix Type Error when Quoting Non-String Values
  frepple/misc/tree.py
Labels: 15.0.project_mi_465

#472 Syncing from upstream frePPLe/odoo (17.0)
  frepple/controllers/outbound.py
Labels: 17.0

#473 Syncing from upstream frePPLe/odoo (14.0)
  .github/workflows/integration_test.yml
Labels: 14.0

#474 Syncing from upstream frePPLe/odoo (15.0)
  .github/workflows/integration_test.yml
Labels: 15.0

#475 Syncing from upstream frePPLe/odoo (16.0)
  .github/workflows/integration_test.yml
Labels: 16.0

#476 Syncing from upstream frePPLe/odoo (17.0)
  .github/workflows/integration_test.yml
Labels: 17.0
